export const CREATE_TICKET = "CREATE_TICKET";
export const RETRIEVE_TICKETS = "RETRIEVE_TICKETS";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";
export const DELETE_ALL_TICKETS = "DELETE_ALL_TICKETS";
